Repository Bauddhik-Geeks/Drum-Kit, pull requests merged in 2021-10, with the labels that each got.

#7 New Changes Done
  images/drum_back.jpeg
  index.html
  styles.css
Labels: hacktoberfest, hactoberfest-accepted

#13 Footer margin fixed and styling added
  README.md
  index.html
  styles.css
Labels: hactoberfest-accepted

#11 Fixes #3
  README.md
Labels: documentation, enhancement
